# Generated by Django 4.2.6 on 2023-10-13 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('flower_type', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
